[package]
name = "embroidery-studio"
version = "0.0.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5.4", features = [] }

[dependencies]
thiserror = "1.0.63"
byteorder = "1.5.0"
encoding_rs = "0.8.34"
memchr = "2.7.4"
hex = "0.4.3"
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
tauri = { version = "1.7.2", features = ["dialog-open", "dialog-save", "fs-read-file", "path-all", "test", "window-close", "window-hide", "window-maximize", "window-minimize", "window-show", "window-start-dragging", "window-unmaximize", "window-unminimize"] }
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1", version = "0.0.0" }
log = "0.4.22"
ordered-float = { version = "4.2.2", features = ["borsh", "serde"] }
borsh = { version = "1.5.1", features = ["derive"] }
quick-xml = "0.36.1"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
