[package]
name = "embroidery-studio"
version = "0.0.0"
edition = "2021"

[profile.dev]
incremental = true

[profile.release]
opt-level = "s"
lto = true
strip = true

[build-dependencies]
tauri-build = { version = "2.0.2", features = [] }

[dependencies]
# Tauri
tauri = { version = "2.0.6", features = ["test"] }
tauri-plugin-dialog = "2.0.3"
tauri-plugin-log = "2.0.1"

# Parsing
byteorder = "1.5.0"
encoding_rs = "0.8.35"
memchr = "2.7.4"
hex = "0.4.3"
quick-xml = "0.37.0"

# Serialization
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
serde_repr = "0.1.19"
borsh = { version = "1.5.1", features = ["derive"] }

# Error handling
anyhow = "1.0.91"

# Logging
log = "0.4.22"

# Other
ordered-float = { version = "4.4.0", features = ["borsh", "serde"] }
