[package]
name = "embroidery-studio"
version = "0.0.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
# Tauri
tauri = { version = "2.0.1", features = ["test"] }
tauri-plugin-dialog = "2.0.1"
tauri-plugin-log = "2.0.1"

# Parsing
byteorder = "1.5.0"
encoding_rs = "0.8.34"
memchr = "2.7.4"
hex = "0.4.3"
quick-xml = "0.36.2"

# Serialization
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
borsh = { version = "1.5.1", features = ["derive"] }

# Error handling
anyhow = "1.0.89"

# Logging
log = "0.4.22"

# Other
ordered-float = { version = "4.2.2", features = ["borsh"] }
