[package]
name = "embroidery-studio"
version = "0.0.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "fs-exists", "path-all", "fs-write-file", "fs-read-file", "dialog-save", "dialog-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1.0.86"
thiserror = "1.0.63"
byteorder = "1.5.0"
encoding_rs = "0.8.34"
memchr = "2.7.4"
hex = "0.4.3"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
