[package]
name = "embroidery-studio"
version = "0.0.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5.4", features = [] }

[dependencies]
thiserror = "1.0.63"
byteorder = "1.5.0"
encoding_rs = "0.8.34"
memchr = "2.7.4"
hex = "0.4.3"
quick-xml = { version = "0.36.1", features = ["serialize"] }
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
tauri = { version = "1.7.2", features = ["dialog-open", "dialog-save", "fs-read-file", "path-all", "window-close", "window-hide", "window-maximize", "window-minimize", "window-show", "window-start-dragging", "window-unmaximize", "window-unminimize"] }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
