[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"

[profile.dev]
debug = "line-tables-only"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
debug = "limited"
strip = "debuginfo"
split-debuginfo = "packed"

[workspace.dependencies]
# Tauri
tauri = { version = "2.5.1", features = ["config-json5"] }
tauri-build = { version = "2.2.0", features = ["config-json5"] }
## Official Tauri plugins
tauri-plugin-clipboard-manager = "2.3.0"
tauri-plugin-dialog = "2.3.0"
tauri-plugin-fs = "2.0.3"
tauri-plugin-log = "2.6.0"
tauri-plugin-opener = "2.4.0"
tauri-plugin-os = "2.3.0"
tauri-plugin-process = "2.3.0"
tauri-plugin-shell = "2.3.0"
tauri-plugin-updater = "2.9.0"
## Third-party Tauri plugins
tauri-plugin-prevent-default = "2.1.2"
tauri-plugin-pinia = "3.7.1"

# Embroiderly Core
embroiderly-parsers = { path = "crates/embroiderly-parsers" }
embroiderly-pattern = { path = "crates/embroiderly-pattern" }
embroiderly-image = { path = "crates/embroiderly-image" }
xsp-parsers = { path = "crates/xsp-parsers" }

# Parsing pattern files
byteorder = "1.5.0"
encoding_rs = "0.8.35"
hex = "0.4.3"
quick-xml = "0.37.5"

# Typst
typst = "0.13.1"
typst-pdf = "0.13.1"
## Third-party Typst libraries
typst-as-lib = "0.14.4"

# Image processing
image = "0.25.6"
quantette = "0.3.0"
palette = "0.7.6"

# Archiving
zip = { version = "4.2.0", features = [
  "zstd",
  "time",
], default-features = false }
zip-extract = { version = "0.4.0", features = [
  "zstd",
  "time",
], default-features = false }

# De/serialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
base64 = "0.22.1"
borsh = { version = "1.5.7", features = ["derive"] }

# CLI
clap = { version = "4.5.40", default-features = false, features = [
  "std",
  "derive",
] }

# Error handling
anyhow = "1.0.98"
thiserror = "2.0.12"

# Logging
log = "0.4.27"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
simple_logger = "5.0.0"

# Other
ordered-float = "5.0.0"
ordermap = "0.5.8"
dyn-clone = "1.0.19"
itertools = "0.14.0"
paste = "1.0.15"
prettydiff = { version = "0.8.1", default-features = false }
rayon = "1.10.0"
tempfile = "3.20.0"
convert_case = "0.8.0"
uuid = { version = "1.17.0", features = ["v4"] }
rand = "0.9.1"
