[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"

[profile.dev]
debug = "line-tables-only"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
debug = "limited"
strip = "debuginfo"
split-debuginfo = "packed"

[workspace.dependencies]
# Tauri
tauri = { version = "2.7.0", features = ["config-json5"] }
tauri-build = { version = "2.4.1", features = ["config-json5"] }
tauri-plugin = { version = "2.4.0", features = ["build"] }
## Official Tauri plugins
tauri-plugin-clipboard-manager = "2.3.0"
tauri-plugin-dialog = "2.3.3"
tauri-plugin-fs = "2.0.3"
tauri-plugin-opener = "2.5.0"
tauri-plugin-os = "2.3.1"
tauri-plugin-process = "2.3.0"
tauri-plugin-shell = "2.3.1"
tauri-plugin-updater = "2.9.0"
## Third-party Tauri plugins
tauri-plugin-prevent-default = "2.1.4"
tauri-plugin-pinia = "3.7.1"
## Custom Tauri plugins
tauri-plugin-log = { path = "crates/tauri-plugin-log" }
tauri-plugin-sentry = { path = "crates/tauri-plugin-sentry" }
tauri-plugin-posthog = { path = "crates/tauri-plugin-posthog" }

# Embroiderly Core
embroiderly-parsers = { path = "crates/embroiderly-parsers" }
embroiderly-pattern = { path = "crates/embroiderly-pattern" }
embroiderly-logger = { path = "crates/embroiderly-logger" }
xsp-parsers = { path = "crates/xsp-parsers" }

# Parsing pattern files
byteorder = "1.5.0"
encoding_rs = "0.8.35"
hex = "0.4.3"
quick-xml = "0.37.5"

# Typst
typst = "0.13.1"
typst-pdf = "0.13.1"
## Third-party Typst libraries
typst-as-lib = "0.14.4"

# Image processing
image = "0.25.6"

# Archiving
zip = { version = "4.6.0", features = [
  "zstd",
  "time",
], default-features = false }

# De/serialization
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
base64 = "0.22.1"
borsh = { version = "1.5.7", features = ["derive"] }

# CLI
clap = { version = "4.5.46", default-features = false, features = [
  "std",
  "derive",
] }

# Error handling
anyhow = "1.0.99"
thiserror = "2.0.16"

# Time handling
time = { version = "0.3.42", features = ["formatting", "macros"] }

# Logging
log = "0.4.27"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
fern = "0.7.1"

# Telemetry
sentry = "0.42.0"
posthog-rs = {version = "0.3.7", default-features = false }

# Identification
machine-uid = "0.5.3"
uuid = { version = "1.18.1", features = ["v4"] }

# Other
ordered-float = { version = "5.0.0" }
dyn-clone = "1.0.20"
itertools = "0.14.0"
paste = "1.0.15"
prettydiff = { version = "0.8.1", default-features = false }
tempfile = "3.21.0"
convert_case = "0.8.0"
rand = "0.9.2"
sha2 = "0.10.9"
