import fs from "node:fs";
import { fileURLToPath, URL } from "node:url";

import js from "@eslint/js";
import vitest from "@vitest/eslint-plugin";
import vuePrettierEslintConfig from "@vue/eslint-config-prettier/skip-formatting";
import { defineConfigWithVueTs, vueTsConfigs } from "@vue/eslint-config-typescript";
import betterTailwindcss from "eslint-plugin-better-tailwindcss";
import importX from "eslint-plugin-import-x";
import noOnlyTests from "eslint-plugin-no-only-tests";
import promise from "eslint-plugin-promise";
import sonarjs from "eslint-plugin-sonarjs";
import unicorn from "eslint-plugin-unicorn";
import vue from "eslint-plugin-vue";
import * as wdio from "eslint-plugin-wdio";
import yml from "eslint-plugin-yml";
import globals from "globals";

// Read the `.prettierignore` file and filter out empty lines and comments.
const ignores = fs
  .readFileSync(fileURLToPath(new URL(".prettierignore", import.meta.url)), { encoding: "utf8" })
  .split(/\r?\n/)
  .filter((s) => s.length && !s.startsWith("#"));

// Ignore autogenerated typings.
ignores.push("app/auto-imports.d.ts", "app/components.d.ts");

export default defineConfigWithVueTs(
  // Common options.
  { ignores },
  js.configs.recommended,

  // High-quality code.
  {
    extends: [promise.configs["flat/recommended"], sonarjs.configs.recommended, unicorn.configs.unopinionated],
    rules: {
      "unicorn/prefer-ternary": "off",
      "unicorn/no-useless-undefined": "off",

      // Enable when Vue.js base TS config's target supports these features.
      "unicorn/no-array-reverse": "off",
      "unicorn/no-array-sort": "off",

      "unicorn/numeric-separators-style": [
        "warn",
        {
          onlyIfContainsSeparator: true,
        },
      ],

      "sonarjs/no-empty-test-file": "off",
      "sonarjs/no-identical-functions": "off",
    },
  },

  // Vue.js configs.
  vue.configs["flat/recommended"],
  vueTsConfigs.recommended,

  // Custom rules.
  {
    files: ["app/src/**/*.{ts,vue}"],
    languageOptions: {
      ecmaVersion: "latest",
      globals: {
        ...globals.builtin,
        ...globals.browser,
      },
    },
    rules: { "no-console": ["warn"] },
  },
  {
    files: ["packages/ui/**/*.{ts,vue}"],
    languageOptions: {
      ecmaVersion: "latest",
      globals: {
        ...globals.builtin,
        ...globals.browser,
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",

      "vue/require-default-prop": "off",
      "vue/multi-word-component-names": "off",
      "vue/no-reserved-component-names": "off",
    },
  },
  {
    files: ["scripts/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      globals: {
        ...globals.builtin,
        ...globals.node,
      },
    },
    rules: {
      "sonarjs/os-command": "off",
      "unicorn/no-process-exit": "off",
    },
  },

  // Testing.
  {
    files: ["app/src/**/*.test.ts", "app/tests/**/*.ts"],
    plugins: { "no-only-tests": noOnlyTests },
  },
  {
    files: ["app/src/**/*.test.ts"],
    extends: [vitest.configs["recommended"]],
  },
  {
    files: ["app/tests/**/*.ts"],
    extends: [wdio.configs["flat/recommended"]],
  },

  // Imports organization.
  {
    files: ["**/*.{js,ts,vue}"],
    plugins: { "import-x": importX },
    rules: {
      "import-x/order": [
        "warn",
        {
          groups: ["builtin", "external", "internal", "parent", "sibling", "index"],
          pathGroups: [
            {
              pattern: "{@embroiderly/**,@tauri-apps/**}",
              group: "external",
              position: "before",
            },
            {
              pattern: "#*/**",
              group: "internal",
            },
            {
              pattern: "virtual:*",
              group: "internal",
              position: "after",
            },
          ],
          pathGroupsExcludedImportTypes: ["builtin"],
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true },
        },
      ],
      "import-x/consistent-type-specifier-style": ["warn", "prefer-top-level"],
    },
  },

  // TailwindCSS classes validation.
  {
    files: ["app/src/**/*.vue"],
    extends: [betterTailwindcss.configs["recommended"]],
    settings: {
      "better-tailwindcss": {
        entryPoint: fileURLToPath(new URL("app/src/app/assets/styles.css", import.meta.url)),
      },
    },
    rules: {
      "better-tailwindcss/enforce-consistent-line-wrapping": ["off"],
    },
  },

  // YAML validation.
  {
    files: ["pnpm-workspace.yaml", ".github/**/*.yml"],
    extends: [yml.configs.recommended],
    rules: {
      "yml/no-empty-mapping-value": "off",
    },
  },

  // Prettier intergation.
  vuePrettierEslintConfig,
);
