import fs from "node:fs";
import { fileURLToPath, URL } from "node:url";

import eslintComments from "@eslint-community/eslint-plugin-eslint-comments";
import vueI18n from "@intlify/eslint-plugin-vue-i18n";
import vitest from "@vitest/eslint-plugin";
import skipFormatting from "@vue/eslint-config-prettier/skip-formatting";
import { defineConfigWithVueTs, vueTsConfigs } from "@vue/eslint-config-typescript";
import betterTailwindcss from "eslint-plugin-better-tailwindcss";
import importX from "eslint-plugin-import-x";
import jsonc from "eslint-plugin-jsonc";
import noOnlyTests from "eslint-plugin-no-only-tests";
import oxlint from "eslint-plugin-oxlint";
import toml from "eslint-plugin-toml";
import vue from "eslint-plugin-vue";
import * as wdio from "eslint-plugin-wdio";
import yml from "eslint-plugin-yml";

// Read the `.prettierignore` file and filter out empty lines and comments.
const ignores = fs
  .readFileSync(fileURLToPath(new URL(".prettierignore", import.meta.url)), { encoding: "utf8" })
  .split(/\r?\n/)
  .filter((s) => s.length && !s.startsWith("#"));

// Ignore autogenerated typings.
ignores.push("app/auto-imports.d.ts", "app/components.d.ts");

export default defineConfigWithVueTs(
  // Common options.
  { ignores },

  // Vue.js configs.
  vue.configs["flat/recommended"],
  vueTsConfigs.recommended,
  {
    files: ["**/*.vue"],
    plugins: {
      "vue-i18n": vueI18n,
      "eslint-comments": eslintComments,
    },
    rules: {
      "vue/block-order": ["error", { order: ["script", "template", "style"] }],
      "vue/define-macros-order": [
        "error",
        { order: ["defineOptions", "defineModel", "defineProps", "defineEmits", "defineSlots"] },
      ],
      "vue/define-props-declaration": ["error", "type-based"],
      "vue/define-emits-declaration": ["error", "type-literal"],
      "vue/prefer-use-template-ref": "error",

      // Disallow raw text in Vue.js component and restrict disabling this rule.
      "vue-i18n/no-raw-text": [
        "error",
        {
          attributes: {
            "/.+/": [
              "title",
              "label",
              "description",
              "help",
              "hint",
              "aria-label",
              "aria-placeholder",
              "placeholder",
              "alt",
            ],
          },
        },
      ],
      "eslint-comments/no-restricted-disable": ["error", "vue-i18n/no-raw-text"],
    },
  },

  // Testing.
  {
    files: ["app/src/**/*.test.ts", "app/tests/**/*.ts"],
    plugins: { "no-only-tests": noOnlyTests },
  },
  {
    files: ["app/src/**/*.test.ts"],
    extends: [vitest.configs["recommended"]],
  },
  {
    files: ["app/tests/**/*.ts"],
    extends: [wdio.configs["flat/recommended"]],
  },

  // Imports organization.
  {
    files: ["**/*.{js,ts,vue}"],
    plugins: { "import-x": importX },
    rules: {
      "import-x/order": [
        "warn",
        {
          groups: ["builtin", "external", "internal", "parent", "sibling", "index"],
          pathGroups: [
            {
              pattern: "{@embroiderly/**,@tauri-apps/**}",
              group: "external",
              position: "before",
            },
            {
              pattern: "#*/**",
              group: "internal",
            },
            {
              pattern: "virtual:*",
              group: "internal",
              position: "after",
            },
          ],
          pathGroupsExcludedImportTypes: ["builtin"],
          "newlines-between": "always",
          alphabetize: {
            order: "asc", // Value imports go first...
            orderImportKind: "desc", // ...then go type imports.
            caseInsensitive: true,
          },
        },
      ],
      "import-x/consistent-type-specifier-style": ["warn", "prefer-top-level"],
    },
  },

  // TailwindCSS classes validation.
  {
    files: ["app/src/**/*.vue"],
    extends: [betterTailwindcss.configs["recommended"]],
    settings: {
      "better-tailwindcss": {
        entryPoint: fileURLToPath(new URL("app/src/app/assets/styles.css", import.meta.url)),
      },
    },
    rules: {
      "better-tailwindcss/enforce-consistent-line-wrapping": ["off"],
    },
  },

  // JSONC validation.
  {
    files: ["**/*.json"],
    ignores: [".oxlintrc.json"],
    extends: [jsonc.configs["flat/recommended-with-json"], jsonc.configs["flat/prettier"]],
  },
  {
    files: [".oxlintrc.json", "**/*.jsonc"],
    extends: [jsonc.configs["flat/recommended-with-jsonc"], jsonc.configs["flat/prettier"]],
  },
  {
    files: ["**/*.json5"],
    extends: [jsonc.configs["flat/recommended-with-json5"], jsonc.configs["flat/prettier"]],
  },
  // TOML validation.
  {
    files: ["**/*.toml"],
    extends: [toml.configs.standard],
  },
  // YAML validation.
  {
    files: ["**/*.yml"],
    extends: [yml.configs.standard, yml.configs.prettier],
    rules: {
      "yml/no-empty-mapping-value": "off",
    },
  },

  ...oxlint.buildFromOxlintConfigFile(".oxlintrc.json"),
  skipFormatting,
);
