packages:
  - app
  - crates/tauri-plugin-*

strictDepBuilds: true
onlyBuiltDependencies: []
ignoredBuiltDependencies: [core-js, esbuild, edgedriver, geckodriver, unrs-resolver, vue-demi]

# Should match Renovate's setting.
minimumReleaseAge: 4320 # 3 days in minutes

trustPolicy: no-downgrade
