[package]
name = "embroiderly-parsers"
edition = "2024"

[dependencies]
# Embroiderly Core
embroiderly-pattern = { path = "../embroiderly-pattern", features = [
  "borsh",
  "serde",
] }

# Parsing pattern files
xsp-parsers = { path = "../xsp-parsers" }
quick-xml = "0.37.5"

# Archiving
zip = { version = "4.0.0", features = [
  "zstd",
  "time",
], default-features = false }
zip-extract = { version = "0.4.0", features = [
  "zstd",
  "time",
], default-features = false }

# Error handling
anyhow = "1.0.98"
thiserror = "2.0.12"

# Logging
log = "0.4.27"

# Other
tempfile = "3.20.0"
