[package]
name = "tauri-plugin-log"
links = "tauri-plugin-log"
edition = { workspace = true }

[build-dependencies]
tauri-plugin = { workspace = true }

[dependencies]
# Tauri
tauri = { workspace = true }

# Logging
log = { workspace = true }
