[test-groups]
# Due to some plugins, which access some system resources for their need, we should run them sequentially to eliminate conflicts.
tauri-commands = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'package(embroiderly) and kind(test)'
test-group = 'tauri-commands'
