name: Audit (frontend)
on:
  workflow_call:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Check types
        run: pnpm build
      - name: Check formatting
        run: pnpm fmt
      - name: Check linting
        run: pnpm lint
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Test
        run: pnpm test
