name: CI (backend)
on:
  pull_request:
    branches: [main, dev]
    types: [opened, reopened, edited, synchronize]
    paths:
      - ".config/**"
      - "app/src-tauri/**"
      - "crates/**"
      - "Cargo.*"
      - rustfmt.toml
      - .github/workflows/ci.backend.yml
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}-backend
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/setup-rust
        with:
          with-nightly: true
      - name: Check formatting
        run: cargo +nightly fmt --check
      - name: Check linting
        run: cargo clippy --locked -- -D warnings
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/setup-rust
      - name: Test
        run: cargo nextest run --locked -F embroiderly/test
