name: CI (backend)
on:
  pull_request:
    branches: [main, dev]
    types: [opened, reopened, edited, synchronize]
    paths:
      - ".config/**"
      - "app/src-tauri/**"
      - "crates/**"
      - "Cargo.*"
      - rustfmt.toml
      - .github/workflows/ci.backend.yml
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}-backend
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-rust
        with:
          stable-components: clippy
          nightly-components: rustfmt
      - name: Check formatting
        run: cargo +nightly fmt --check
      - name: Check linting
        run: cargo clippy --locked -- -D warnings

  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-rust
        with:
          tools: cargo-nextest
      - name: Test
        run: cargo nextest run --locked -F embroiderly/test
