name: CI (backend)
on:
  pull_request:
    branches: [main, dev]
    types: [opened, reopened, edited, synchronize]
    paths:
      - ".config/**"
      - "app/src-tauri/**"
      - "crates/**"
      - "Cargo.*"
      - rustfmt.toml
      - .github/workflows/ci.backend.yml
      - .github/codecov.yml
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}-backend
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-rust
        with:
          stable-components: clippy
          nightly-components: rustfmt
      - name: Check formatting
        run: cargo +nightly fmt --check
      - name: Check linting
        run: cargo clippy --locked -- -D warnings

  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-rust
        with:
          nightly-components: llvm-tools-preview
          tools: cargo-nextest,cargo-llvm-cov

      # Build sidecars to replace stubs, otherwise cargo-llvm-cov fails on invalid executables.
      - name: Build sidecars
        shell: bash
        run: |
          TRIPLE=$(rustc -vV | grep 'host:' | sed 's/host: //')

          EXT=""
          if [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
            EXT=".exe"
          fi

          cargo build -p embroiderly_image -p embroiderly_publish

          mv "target/debug/embroiderly_image${EXT}" "app/src-tauri/binaries/embroiderly_image-${TRIPLE}${EXT}"
          mv "target/debug/embroiderly_publish${EXT}" "app/src-tauri/binaries/embroiderly_publish-${TRIPLE}${EXT}"

      - name: Test
        run: cargo +nightly llvm-cov nextest --locked -F embroiderly/test --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        if: matrix.platform == 'ubuntu-latest'
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          flags: backend
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
