name: CI (frontend)
on:
  pull_request:
    branches: [main, dev]
    types: [opened, reopened, edited, synchronize]
    paths:
      - "app/**"
      - "!app/src-tauri/**"
      - "docs/**"
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - eslint.config.js
      - .prettierrc.json
      - .prettierignore
      - .github/workflows/ci.frontend.yml
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}-frontend
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-node
      - name: Check types
        run: pnpm check-types
      - name: Check formatting
        run: pnpm fmt
      - name: Check linting
        run: pnpm lint
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./.github/actions/setup-node
      - name: Test
        run: pnpm test
