name: CI (frontend)
on:
  pull_request:
    branches: [main, dev]
    types: [opened, reopened, edited, synchronize]
    paths:
      - "app/**"
      - "!app/src-tauri/**"
      - "package*.json"
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - eslint.config.js
      - .prettierrc.json
      - .prettierignore
      - .github/workflows/ci.frontend.yml
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}-frontend
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/setup-node
      - name: Check types
        run: pnpm build
      - name: Check formatting
        run: pnpm fmt
      - name: Check linting
        run: pnpm lint
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/setup-node
      - name: Test
        run: pnpm test
