name: CI (frontend)
on:
  pull_request:
    branches: [main, dev]
    types: [opened, reopened, edited, synchronize]
    paths:
      - "app/**"
      - "!app/src-tauri/**"
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - eslint.config.js
      - .prettierrc.json
      - .prettierignore
      - .github/workflows/ci.frontend.yml
      - .github/codecov.yml
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}-frontend
  cancel-in-progress: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/actions/setup-node
      - name: Check types
        run: pnpm build
      - name: Check formatting
        run: pnpm fmt
      - name: Check linting
        run: pnpm lint
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/actions/setup-node
      - name: Test
        run: pnpm test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          flags: frontend
          token: ${{ secrets.CODECOV_TOKEN }}
