name: CI (integration)
on:
  pull_request:
    branches: [main, dev]
    types: [opened, reopened, edited, synchronize]
    paths:
      - "app/**"
      - "crates/**"
      - package.json
      - Cargo.toml
      - .github/workflows/ci.integration.yml
permissions:
  contents: read
concurrency:
  group: ${{ github.ref }}-integration
  cancel-in-progress: true
jobs:
  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-rust
        with:
          tools: tauri-driver

      - name: Install system webdriver (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install -y webkit2gtk-driver xvfb xdg-user-dirs

      - name: Install system webdriver (Windows)
        if: matrix.platform == 'windows-latest'
        run: cargo install --git https://github.com/chippers/msedgedriver-tool

      - name: Run WebdriverIO test suite (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          xdg-user-dirs-update
          source ${HOME}/.config/user-dirs.dirs
          xvfb-run pnpm --filter @embroiderly/app test:e2e

      - name: Run WebdriverIO test suite (Windows)
        if: matrix.platform == 'windows-latest'
        run: pnpm --filter @embroiderly/app test:e2e
