name: Documentation
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]
    types: [opened, reopened, edited, synchronize]
    paths:
      - "docs/**"
      - .github/docs.yml
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: ${{ github.ref }}-docs
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: docs/
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/actions/setup-node

      - name: Install Inter Font
        run: |
          sudo apt update
          sudo apt install -y fonts-inter

      - name: Install Typst
        uses: taiki-e/install-action@4575ae687efd0e2c78240087f26013fb2484987f # v2.62.6
        with:
          tool: typst-cli

      - name: Build Documentation
        run: pnpm run build

      - name: Deploy to Cloudflare
        id: deploy
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: ${{ github.ref == 'refs/heads/main' && 'deploy' || 'versions upload' }}
          workingDirectory: docs/

      - name: Post Comment
        run: |
          TAG="<!--embroiderly-documentation-->"
          MESSAGE="See the Embroiderly Documentation preview at <$DEPLOY_URL>."

          COMMENT_ID=$(gh pr view ${{ github.event.pull_request.number }} --json comments --jq ".comments[] | select(.body | contains(\"$TAG\")) | .id" | head -n 1)
          if [ -z "$COMMENT_ID" ]; then
            gh pr comment ${{ github.event.pull_request.number }} --body "$TAG$MESSAGE"
          else
            gh api repos/:owner/:repo/issues/comments/$COMMENT_ID -X PATCH -f body="$TAG$MESSAGE"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          DEPLOY_URL: ${{ steps.deploy.outputs.deployment-url }}
