name: Test Release
on:
  pull_request:
    branches: ["main"]
    types: ["opened", "reopened", "edited", "synchronize"]
permissions:
  contents: read
env:
  CARGO_TERM_COLOR: always
jobs:
  audit-frontend:
    uses: ./.github/workflows/audit.frontend.yml
  audit-backend:
    uses: ./.github/workflows/audit.backend.yml
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v5
      - name: Install system dependencies (Ubuntu-only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: pnpm
      - run: pnpm install
      - uses: dtolnay/rust-toolchain@stable
      - uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          EMBROIDERLY_POSTHOG_API_KEY: ${{ secrets.EMBROIDERLY_POSTHOG_API_KEY }}
          EMBROIDERLY_SENTRY_DSN: ${{ secrets.EMBROIDERLY_SENTRY_DSN }}
          EMBROIDERLY_PUBLISH_SENTRY_DSN: ${{ secrets.EMBROIDERLY_PUBLISH_SENTRY_DSN }}
        with:
          updaterJsonPreferNsis: true
