name: Release
on:
  push:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    outputs:
      app-version: ${{ steps.tauri.outputs.appVersion }}
    steps:
      - uses: actions/checkout@v5
      - name: Install system dependencies (Ubuntu-only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: pnpm
      - uses: dtolnay/rust-toolchain@stable

      - run: pnpm install

      - name: Build the application
        id: tauri
        uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          EMBROIDERLY_SENTRY_DSN: ${{ secrets.EMBROIDERLY_SENTRY_DSN }}
          EMBROIDERLY_PUBLISH_SENTRY_DSN: ${{ secrets.EMBROIDERLY_PUBLISH_SENTRY_DSN }}
        with:
          tagName: v__VERSION__
          releaseName: Embroiderly v__VERSION__
          updaterJsonPreferNsis: true

      - name: Upload debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: debug-symbols-${{ matrix.platform }}
          path: target/release/embroiderly.(pdb|dwp)
          retention-days: 1

  sentry:
    needs: release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: embroidery-space
      SENTRY_PROJECT: embroiderly
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install

      - name: Install Sentry CLI
        run: pnpm install -g @sentry/cli

      - name: Create Sentry release
        run: |
          sentry-cli releases new "${{ needs.release.outputs.app-version }}"
          sentry-cli releases set-commits "${{ needs.release.outputs.app-version }}" --auto || true

      - name: Build frontend with source maps
        env:
          TAURI_ENV_DEBUG: "true"
        run: pnpm build

      - name: Upload source maps to Sentry
        run: |
          sentry-cli sourcemaps inject ./app/dist
          sentry-cli sourcemaps upload --release="${{ needs.release.outputs.app-version }}" ./app/dist

      - name: Download debug symbols
        uses: actions/download-artifact@v4
        with:
          pattern: debug-symbols-*
          merge-multiple: true

      - name: Upload debug symbols to Sentry
        run: |
          find . -name "embroiderly.pdb" -exec sentry-cli debug-files upload --release="${{ needs.release.outputs.app-version }}" {} + || true
          find . -name "embroiderly.dwp" -exec sentry-cli debug-files upload --release="${{ needs.release.outputs.app-version }}" {} + || true

      - name: Finalize Sentry release
        run: sentry-cli releases finalize "${{ needs.release.outputs.app-version }}"

  build-sidecars:
    needs: release
    uses: ./.github/workflows/build-sidecars.yml
    with:
      app-version: ${{ needs.release.outputs.app-version }}
    secrets: inherit
