name: Release
on:
  push:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    outputs:
      app-version: ${{ steps.tauri.outputs.appVersion }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install system dependencies (Ubuntu-only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: package.json
          cache: pnpm
      - uses: dtolnay/rust-toolchain@1.89.0 # stable

      - run: pnpm install

      - name: Build the application
        id: tauri
        uses: tauri-apps/tauri-action@e834788a94591d81e3ae0bd9ec06366f5afb8994 # v0.5.23
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          EMBROIDERLY_POSTHOG_API_KEY: ${{ secrets.EMBROIDERLY_POSTHOG_API_KEY }}
          EMBROIDERLY_SENTRY_DSN: ${{ secrets.EMBROIDERLY_SENTRY_DSN }}
          EMBROIDERLY_PUBLISH_SENTRY_DSN: ${{ secrets.EMBROIDERLY_PUBLISH_SENTRY_DSN }}
        with:
          tagName: v__VERSION__
          releaseName: Embroiderly v__VERSION__
          updaterJsonPreferNsis: true

      - name: Upload debug symbols
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: debug-symbols-${{ matrix.platform }}
          path: |
            target/release/embroiderly.pdb
            target/release/embroiderly.dwp
          retention-days: 1

  sentry:
    needs: release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: embroidery-space
      SENTRY_PROJECT: embroiderly
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install

      - name: Install Sentry CLI
        run: pnpm install -g @sentry/cli

      - name: Create Sentry release
        run: |
          sentry-cli releases new "${{ needs.release.outputs.app-version }}"
          sentry-cli releases set-commits "${{ needs.release.outputs.app-version }}" --auto || true

      - name: Build frontend with source maps
        env:
          TAURI_ENV_DEBUG: "true"
        run: pnpm build

      - name: Upload source maps to Sentry
        run: |
          sentry-cli sourcemaps inject ./app/dist
          sentry-cli sourcemaps upload --release="${{ needs.release.outputs.app-version }}" ./app/dist

      - name: Download debug symbols
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          pattern: debug-symbols-*
          merge-multiple: true

      - name: Upload debug symbols to Sentry
        run: |
          find . -name "embroiderly.pdb" -exec sentry-cli debug-files upload {} + || true
          find . -name "embroiderly.dwp" -exec sentry-cli debug-files upload {} + || true

      - name: Finalize Sentry release
        run: sentry-cli releases finalize "${{ needs.release.outputs.app-version }}"

  build-sidecars:
    needs: release
    permissions:
      contents: write
    uses: ./.github/workflows/build-sidecars.yml
    with:
      app-version: ${{ needs.release.outputs.app-version }}
    secrets: inherit
