name: Test Release
on:
  pull_request:
    branches: ["main"]
    types: ["opened", "reopened", "edited", "synchronize"]
env:
  CARGO_TERM_COLOR: always
jobs:
  audit-frontend:
    uses: ./.github/workflows/reusable/frontend.yml
  audit-backend:
    uses: ./.github/workflows/reusable/backend.yml
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies (Ubuntu-only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - uses: dtolnay/rust-toolchain@stable
      - run: npm ci
      # This step is necessary to initially build the Embroiderly.
      # Before bundling, the actual sidecar binary will be created and bundled with the application.
      - name: Create dummy embroiderly-publish sidecar binaries
        run: sh ./scripts/create-dummy-embroiderly-publish-sidecar.sh
      - uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          updaterJsonPreferNsis: true
